CREATE TABLE IF NOT EXISTS users
(
    "userId"  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "name"    VARCHAR NOT NULL,
    "surname" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS cards
(
    "id"       INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "userId"   INTEGER NOT NULL,
    "password" VARCHAR NOT NULL,
    "currency" VARCHAR NOT NULL,
    "value"    DECIMAL NOT NULL,
    "credit"   DECIMAL NOT NULL,
    "blocked"  BOOLEAN NOT NULL default FALSE
);


ALTER TABLE cards
    ADD CONSTRAINT "userFK" FOREIGN KEY ("userId") REFERENCES users ("userId") ON UPDATE CASCADE ON DELETE CASCADE